### ISSUE TITLE
Clicking on waterfall on smaller viewport loads the wrong resource

### ISSUE THREAD

**Issue by tunetheweb** [catchpoint/WebPageTest#1631]
## Description

Super weird one this.

Run a webpage test. Here's an example: 
![image](https://user-images.githubusercontent.com/10931297/142737582-b7cbdfab-e646-4b6e-9c9d-78acc55f93e4.png)

Open the waterfall for one of the runs and click on a request.

![image](https://user-images.githubusercontent.com/10931297/142737606-5087873a-426a-4aad-83cd-f369d58542ca.png)

Make the window smaller (or switch to mobile view - but also seems to happen with 1400 width) and click on a resource. Note it loads the NEXT resource instead:

![image](https://user-images.githubusercontent.com/10931297/142737656-7d69311a-de8c-42ba-9ac0-0ad5c166e51d.png)

You can see from that last screenshot that the hover effort, as well as the colour of the selected resource, clearly shows I clicked 2 -  but it loaded resource 3?!?

Very odd.

### Expected result
Loads the resource I clicked on and acts consistently no matter what the viewport size.

### Actual result
Loads wrong resource

### Related issues?
Had a quick search but couldn't find one.

**Comment by tigt** [comment]
Can confirm by popping open DevTools on the side: every `.request-overlay` is shifted up by one, and `#request-overlay-step1-1` even shifts over the chart’s top header row.

For me, the exact breakpoint where the bug happens is `window.innerWidth` of 1013 to 1012 pixels, and luckily there’s a media query exactly there:

```css
@media (max-width: 1012px) {
    /* … */
    div.waterfall-container,
    div.overflow-container {
        position: relative;
        left: 0;
        top: 0;
        clear: both;
        text-align: left;
        width: 100% !important;
        margin: auto;
        overflow: hidden;
        overflow-x: auto;
        padding-top: 1em;
    }
   /* … */
}
```

If I remove the `padding-top: 1em;` from `.waterfall-container`, then the bug disappears. Looks like that’s the culprit.
